### ISSUE TITLE
Adjust the block reward to use the seesaw Algo for PIVX

### ISSUE THREAD

**Issue by PIVX-Project** [PIVXMasterNodeDev/PIVXMasterNode#1]
the see-saw algo, is how the system changes the block rewards from the masternode to the staker. Also, I notice you have the reward set at 2.5, when the actuall block reward is (5 PIV -10% (budget) which is 4.5, and that reward is then distributed to the masternodes and staking wallets, based on the amount of masternodes that exist on the network. as the number drop, the masternode reward increases, and as the number of masternodes increases past a certain point, the reward decreases..

**Comment by JSponaugle** [comment]
Resolved with coin.php update
